"""产品属性模板（对标店小秘 IGNITION_COIL 等汽配类字段，后续由领星 Schema 动态替换）。"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

MOCK_ATTRIBUTE_FIELDS: list[dict[str, Any]] = [
    {
        "key": "model_number",
        "label_en": "Model Number",
        "label_zh": "型号",
        "type": "text",
        "required": True,
        "placeholder": "",
    },
    {
        "key": "model_name",
        "label_en": "Model Name",
        "label_zh": "型号名称",
        "type": "text",
        "required": True,
        "placeholder": "",
    },
    {
        "key": "number_of_items",
        "label_en": "Number of Items",
        "label_zh": "产品数量",
        "type": "number",
        "required": True,
        "default": "1",
        "step": "1",
        "min": "1",
    },
    {
        "key": "exterior_finish",
        "label_en": "Exterior Finish",
        "label_zh": "外饰面",
        "type": "select",
        "searchable": True,
        "required": True,
        "default": "machined",
        "options": [
            {"value": "brushed", "label": "Brushed(拉丝)"},
            {"value": "chrome", "label": "Chrome(铬)"},
            {"value": "machined", "label": "Machined(机加工)"},
            {"value": "milled", "label": "Milled(铣削)"},
            {"value": "painted", "label": "Painted(已涂漆)"},
            {"value": "polished", "label": "Polished(抛光)"},
        ],
    },
    {
        "key": "part_number",
        "label_en": "Part Number",
        "label_zh": "零件编号",
        "type": "text",
        "required": True,
        "placeholder": "",
    },
    {
        "key": "included_components",
        "label_en": "Included Components",
        "label_zh": "所包含组件",
        "type": "checkbox_group",
        "layout": "inline",
        "editable_options": True,
        "allow_other": True,
        "required": True,
        "options": [],
    },
    {
        "key": "automotive_fit_type",
        "label_en": "Automotive Fit Type",
        "label_zh": "汽车适配类型",
        "type": "select",
        "required": True,
        "default": "vehicle_specific_fit",
        "options": [
            {"value": "vehicle_specific_fit", "label": "Vehicle Specific Fit(特定车型)"},
            {"value": "universal_fit", "label": "Universal Fit(通用)"},
        ],
    },
    {"type": "subsection", "title": "List Price(不含税价目表)"},
    {
        "key": "list_price_currency",
        "label_en": "List Price Currency",
        "label_zh": "价目表货币",
        "type": "select",
        "required": True,
        "options": [
            {"value": "USD", "label": "USD(美元)"},
            {"value": "CAD", "label": "CAD(加元)"},
            {"value": "MXN", "label": "MXN(墨西哥比索)"},
        ],
    },
    {
        "key": "list_price",
        "label_en": "List Price",
        "label_zh": "不含税价目表",
        "type": "number",
        "required": True,
        "step": "0.01",
        "min": "0",
        "placeholder": "",
    },
    {"type": "subsection", "title": "Item Package Dimensions(包装尺寸)", "panel": True},
    {
        "key": "item_package_length",
        "label_en": "Item Package Length",
        "label_zh": "包装长度",
        "type": "unit",
        "unit_key": "item_package_length_unit",
        "default": "0.35",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {
        "key": "item_package_width",
        "label_en": "Item Package Width",
        "label_zh": "包装宽度",
        "type": "unit",
        "unit_key": "item_package_width_unit",
        "default": "0.16",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {
        "key": "item_package_height",
        "label_en": "Item Package Height",
        "label_zh": "包装高度",
        "type": "unit",
        "unit_key": "item_package_height_unit",
        "default": "0.08",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {"type": "subsection", "title": "Package Weight(包裹重量)", "panel": True},
    {
        "key": "item_package_weight",
        "label_en": "Package Weight",
        "label_zh": "包装重量",
        "type": "unit",
        "unit_key": "item_package_weight_unit",
        "default": "0.15",
        "unit_default": "kilograms",
        "unit_options": [
            {"value": "kilograms", "label": "Kilograms(公斤)"},
            {"value": "pounds", "label": "Pounds(磅)"},
        ],
    },
    {
        "key": "country_of_origin",
        "label_en": "Country of Origin",
        "label_zh": "原产国",
        "type": "select",
        "required": True,
        "default": "CN",
        "options": [
            {"value": "CN", "label": "China(中国)"},
            {"value": "US", "label": "United States(美国)"},
            {"value": "DE", "label": "Germany(德国)"},
        ],
    },
    {
        "key": "warranty_description",
        "label_en": "Warranty Description",
        "label_zh": "保修说明",
        "type": "checkbox_group",
        "options": ["2 years"],
        "allow_other": True,
        "editable_options": True,
        "default": "2 years",
    },
    {
        "key": "supplier_declared_dg_hz_regulation",
        "label_en": "Dangerous Goods Regulations",
        "label_zh": "危险商品规管",
        "type": "checkbox_group",
        "required": True,
        "layout": "grid",
        "columns": 4,
        "options": [
            "ghs",
            "not_applicable",
            "unknown",
            "other",
            "storage",
            "transportation",
            "waste",
        ],
        "option_labels": {
            "ghs": "GHS(全球统一制度)",
            "not_applicable": "Not Applicable(不适用)",
            "unknown": "Unknown(未知)",
            "other": "Other(其他)",
            "storage": "Storage(存储)",
            "transportation": "Transportation(运输)",
            "waste": "Waste(废物)",
        },
        "default": "not_applicable",
    },
    {
        "key": "number_of_boxes",
        "label_en": "Number of Boxes",
        "label_zh": "箱数",
        "type": "number",
        "required": True,
        "default": "1",
        "step": "1",
        "min": "1",
    },
    {
        "key": "contains_liquid_contents",
        "label_en": "Contains Liquid Contents?",
        "label_zh": "是否含液体",
        "type": "select",
        "required": True,
        "default": "false",
        "options": [
            {"value": "false", "label": "No(否)"},
            {"value": "true", "label": "Yes(是)"},
        ],
    },
    {
        "key": "is_assembly_required",
        "label_en": "Required Assembly",
        "label_zh": "需要组装",
        "type": "select",
        "required": True,
        "default": "false",
        "options": [
            {"value": "false", "label": "No(不)"},
            {"value": "true", "label": "Yes(是)"},
        ],
    },
    {
        "key": "required_product_compliance_certificate",
        "label_en": "Product Compliance Certificate",
        "label_zh": "产品合规证书",
        "type": "select",
        "searchable": True,
        "searchable_mode": "dropdown",
        "required": True,
        "default": "Not Applicable",
        "options": [
            {
                "value": "California Air Review Board (CARB)",
                "label": "California Air Review Board (CARB)(加州空气资源委员会)",
            },
            {"value": "Not Applicable", "label": "Not Applicable(不适用)"},
        ],
    },
]


MOCK_HEADPHONES_FIELDS: list[dict[str, Any]] = [
    {
        "key": "headphones_form_factor",
        "label_en": "Headphones Form Factor",
        "label_zh": "耳机形态",
        "type": "select",
        "required": True,
        "options": [
            {"value": "over_ear", "label": "Over Ear(头戴式)"},
            {"value": "in_ear", "label": "In Ear(入耳式)"},
            {"value": "on_ear", "label": "On Ear(贴耳式)"},
        ],
    },
    {
        "key": "connectivity_technology",
        "label_en": "Connectivity Technology",
        "label_zh": "连接方式",
        "type": "select",
        "required": True,
        "options": [
            {"value": "wireless", "label": "Wireless(无线)"},
            {"value": "wired", "label": "Wired(有线)"},
        ],
    },
    {
        "key": "model_number",
        "label_en": "Model Number",
        "label_zh": "型号",
        "type": "text",
        "required": True,
    },
    {
        "key": "model_name",
        "label_en": "Model Name",
        "label_zh": "型号名称",
        "type": "text",
        "required": True,
    },
    {
        "key": "number_of_items",
        "label_en": "Number of Items",
        "label_zh": "产品数量",
        "type": "number",
        "required": True,
        "default": "1",
    },
    {"type": "subsection", "title": "List Price(不含税价目表)"},
    {
        "key": "list_price_currency",
        "label_en": "List Price Currency",
        "label_zh": "价目表货币",
        "type": "select",
        "required": True,
        "default": "USD",
        "options": [{"value": "USD", "label": "USD"}, {"value": "CAD", "label": "CAD"}],
    },
    {
        "key": "list_price",
        "label_en": "List Price",
        "label_zh": "不含税价目表",
        "type": "number",
        "required": True,
    },
    {"type": "subsection", "title": "Item Package Dimensions(包装尺寸)", "panel": True},
    {
        "key": "item_package_length",
        "label_en": "Item Package Length",
        "label_zh": "包装长度",
        "type": "unit",
        "required": True,
        "unit_key": "item_package_length_unit",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {
        "key": "item_package_width",
        "label_en": "Item Package Width",
        "label_zh": "包装宽度",
        "type": "unit",
        "required": True,
        "unit_key": "item_package_width_unit",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {
        "key": "item_package_height",
        "label_en": "Item Package Height",
        "label_zh": "包装高度",
        "type": "unit",
        "required": True,
        "unit_key": "item_package_height_unit",
        "unit_default": "inches",
        "unit_options": [
            {"value": "inches", "label": "Inches(英寸)"},
            {"value": "centimeters", "label": "Centimeters(厘米)"},
        ],
    },
    {"type": "subsection", "title": "Package Weight(包裹重量)", "panel": True},
    {
        "key": "item_package_weight",
        "label_en": "Package Weight",
        "label_zh": "包装重量",
        "type": "unit",
        "required": True,
        "unit_key": "item_package_weight_unit",
        "unit_default": "pounds",
        "unit_options": [
            {"value": "pounds", "label": "Pounds(磅)"},
            {"value": "kilograms", "label": "Kilograms(公斤)"},
        ],
    },
    {
        "key": "country_of_origin",
        "label_en": "Country of Origin",
        "label_zh": "原产国",
        "type": "select",
        "required": True,
        "default": "CN",
        "options": [{"value": "CN", "label": "China(中国)"}, {"value": "US", "label": "United States(美国)"}],
    },
    {
        "key": "supplier_declared_dg_hz_regulation",
        "label_en": "Dangerous Goods Regulations",
        "label_zh": "危险商品规管",
        "type": "checkbox_group",
        "required": True,
        "layout": "grid",
        "columns": 4,
        "options": ["not_applicable", "ghs", "unknown", "other"],
        "default": "not_applicable",
    },
]


def get_mock_attributes(product_type: str) -> list[dict[str, Any]]:
    product_type = (product_type or "AUTO_PART").strip().upper()
    if product_type == "HEADPHONES":
        return deepcopy(MOCK_HEADPHONES_FIELDS)
    return deepcopy(MOCK_ATTRIBUTE_FIELDS)
